# Site settings
title: Keffa.se
email: 
description: > # this means to ignore newlines until "baseurl:"
  Keffa.se är familjen Nilssons domän
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.keffa.se" # the base hostname & protocol for your site
twitter_username: 
github_username:

# Build settings
markdown: RedCloth
